name: Build Scanner

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup Developer CMD
      uses: ilammy/msvc-dev-cmd@v1.12.1

    - name: Build scanner.sln
      run: |
        msbuild scanner.sln /p:Configuration=Release /p:Platform=Win32 /m

    - name: Upload scanner.exe
      uses: actions/upload-artifact@v4
      with:
        name: scanner
        path: "**/Release/*.exe"
